// User
export const  CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const  CREATE_USER_LOADING = "CREATE_USER_LOADING";
export const  CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const  UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const  UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const  UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const  DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const  DELETE_USER_FAILED = "DELETE_USER_FAILED";
export const  DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const  GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const  GET_USER_FAILED = "GET_USER_FAILED";
export const  GET_USER_LOADING = "GET_USER_LOADING";
export const  GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const  GET_USERS_FAILED = "GET_USERS_FAILED";
export const  GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_ME_SUCCESS="GET_ME_SUCCESS";
export const GET_ME_FAILED="GET_ME_FAILED";
export const GET_ME_LOADING ="GET_ME_LOADING";

//stats  
export const GET_STATS_SUCCESS="GET_STATS_SUCCESS";
export const GET_STATS_FAILED ="GET_STATS_FAILED";
export const GET_STATS_LOADING ="GET_STATS_LOADING"; 


// Announcement 
export const  CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS";
export const  CREATE_ANNOUNCEMENT_LOADING = "CREATE_ANNOUNCEMENT_LOADING";
export const  CREATE_ANNOUNCEMENT_FAILED = "CREATE_ANNOUNCEMENT_FAILED";
export const  UPDATE_ANNOUNCEMENT_SUCCESS = "UPDATE_ANNOUNCEMENT_SUCCESS";
export const  UPDATE_ANNOUNCEMENT_LOADING = "UPDATE_ANNOUNCEMENT_LOADING";
export const  UPDATE_ANNOUNCEMENT_FAILED = "UPDATE_ANNOUNCEMENT_FAILED";
export const  DELETE_ANNOUNCEMENT_SUCCESS = "DELETE_ANNOUNCEMENT_SUCCESS";
export const  DELETE_ANNOUNCEMENT_FAILED = "DELETE_ANNOUNCEMENT_FAILED";
export const  DELETE_ANNOUNCEMENT_LOADING = "DELETE_ANNOUNCEMENT_LOADING";
export const  GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
export const  GET_ANNOUNCEMENT_FAILED = "GET_ANNOUNCEMENT_FAILED";
export const  GET_ANNOUNCEMENT_LOADING = "GET_ANNOUNCEMENT_LOADING";
export const  GET_ANNOUNCEMENTS_SUCCESS = "GET_ANNOUNCEMENTS_SUCCESS";
export const  GET_ANNOUNCEMENTS_FAILED = "GET_ANNOUNCEMENTS_FAILED";
export const  GET_ANNOUNCEMENTS_LOADING = "GET_ANNOUNCEMENTS_LOADING";


//article
export const  CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const  CREATE_ARTICLE_LOADING = "CREATE_ARTICLE_LOADING";
export const  CREATE_ARTICLE_FAILED = "CREATE_ARTICLE_FAILED";
export const  UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const  UPDATE_ARTICLE_LOADING = "UPDATE_ARTICLE_LOADING";
export const  UPDATE_ARTICLE_FAILED = "UPDATE_ARTICLE_FAILED";
export const  DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const  DELETE_ARTICLE_FAILED = "DELETE_ARTICLE_FAILED";
export const  DELETE_ARTICLE_LOADING = "DELETE_ARTICLE_LOADING";
export const  GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const  GET_ARTICLE_FAILED = "GET_ARTICLE_FAILED";
export const  GET_ARTICLE_LOADING = "GET_ARTICLE_LOADING";
export const  GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const  GET_ARTICLES_FAILED = "GET_ARTICLES_FAILED";
export const  GET_ARTICLES_LOADING = "GET_ARTICLES_LOADING";

// auth
export const  LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const  LOGIN_AUTH_LOADING = "LOGIN_AUTH_LOADING";
export const  LOGIN_AUTH_FAILED = "LOGIN_AUTH_FAILED";
export const  REFRESH_AUTH_SUCCESS = "REFRESH_AUTH_SUCCESS";
export const  REFRESH_AUTH_LOADING = "REFRESH_AUTH_LOADING";
export const  REFRESH_AUTH_FAILED = "REFRESH_AUTH_FAILED";
export const  SIGNUP_AUTH_SUCCESS = "SIGNUP_AUTH_SUCCESS";
export const  SIGNUP_AUTH_LOADING = "SIGNUP_AUTH_LOADING";
export const  SIGNUP_AUTH_FAILED = "SIGNUP_AUTH_FAILED";
export const LOGOUT="LOGOUT";


// category 
export const  CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const  CREATE_CATEGORY_LOADING = "CREATE_CATEGORY_LOADING";
export const  CREATE_CATEGORY_FAILED = "CREATE_CATEGORY_FAILED";
export const  UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const  UPDATE_CATEGORY_LOADING = "UPDATE_CATEGORY_LOADING";
export const  UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";
export const  DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const  DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";
export const  DELETE_CATEGORY_LOADING = "DELETE_CATEGORY_LOADING";
export const  GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const  GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";
export const  GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING";
export const  GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const  GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";
export const  GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING";

// certificate
export const  CREATE_CERTIFICATE_SUCCESS = "CREATE_CERTIFICATE_SUCCESS";
export const  CREATE_CERTIFICATE_LOADING = "CREATE_CERTIFICATE_LOADING";
export const  CREATE_CERTIFICATE_FAILED = "CREATE_CERTIFICATE_FAILED";
export const  UPDATE_CERTIFICATE_SUCCESS = "UPDATE_CERTIFICATE_SUCCESS";
export const  UPDATE_CERTIFICATE_LOADING = "UPDATE_CERTIFICATE_LOADING";
export const  UPDATE_CERTIFICATE_FAILED = "UPDATE_CERTIFICATE_FAILED";
export const  DELETE_CERTIFICATE_SUCCESS = "DELETE_CERTIFICATE_SUCCESS";
export const  DELETE_CERTIFICATE_FAILED = "DELETE_CERTIFICATE_FAILED";
export const  DELETE_CERTIFICATE_LOADING = "DELETE_CERTIFICATE_LOADING";
export const  GET_CERTIFICATE_SUCCESS = "GET_CERTIFICATE_SUCCESS";
export const  GET_CERTIFICATE_FAILED = "GET_CERTIFICATE_FAILED";
export const  GET_CERTIFICATE_LOADING = "GET_CERTIFICATE_LOADING";
export const  GET_CERTIFICATES_SUCCESS = "GET_CERTIFICATES_SUCCESS";
export const  GET_CERTIFICATES_FAILED = "GET_CERTIFICATES_FAILED";
export const  GET_CERTIFICATES_LOADING = "GET_CERTIFICATES_LOADING";

// courses 
export const  CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const  CREATE_COURSE_LOADING = "CREATE_COURSE_LOADING";
export const  CREATE_COURSE_FAILED = "CREATE_COURSE_FAILED";
export const  UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const  UPDATE_COURSE_LOADING = "UPDATE_COURSE_LOADING";
export const  UPDATE_COURSE_FAILED = "UPDATE_COURSE_FAILED";
export const  DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const  DELETE_COURSE_FAILED = "DELETE_COURSE_FAILED";
export const  DELETE_COURSE_LOADING = "DELETE_COURSE_LOADING";
export const  GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const  GET_COURSE_FAILED = "GET_COURSE_FAILED";
export const  GET_COURSE_LOADING = "GET_COURSE_LOADING";
export const  GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const  GET_COURSES_FAILED = "GET_COURSES_FAILED";
export const  GET_COURSES_LOADING = "GET_COURSES_LOADING";

// complain
export const  CREATE_COMPLAIN_SUCCESS = "CREATE_COMPLAIN_SUCCESS";
export const  CREATE_COMPLAIN_LOADING = "CREATE_COMPLAIN_LOADING";
export const  CREATE_COMPLAIN_FAILED = "CREATE_COMPLAIN_FAILED";
export const  UPDATE_COMPLAIN_SUCCESS = "UPDATE_COMPLAIN_SUCCESS";
export const  UPDATE_COMPLAIN_LOADING = "UPDATE_COMPLAIN_LOADING";
export const  UPDATE_COMPLAIN_FAILED = "UPDATE_COMPLAIN_FAILED";
export const  DELETE_COMPLAIN_SUCCESS = "DELETE_COMPLAIN_SUCCESS";
export const  DELETE_COMPLAIN_FAILED = "DELETE_COMPLAIN_FAILED";
export const  DELETE_COMPLAIN_LOADING = "DELETE_COMPLAIN_LOADING";
export const  GET_COMPLAIN_SUCCESS = "GET_COMPLAIN_SUCCESS";
export const  GET_COMPLAIN_FAILED = "GET_COMPLAIN_FAILED";
export const  GET_COMPLAIN_LOADING = "GET_COMPLAIN_LOADING";
export const  GET_COMPLAINS_SUCCESS = "GET_COMPLAINS_SUCCESS";
export const  GET_COMPLAINS_FAILED = "GET_COMPLAINS_FAILED";
export const  GET_COMPLAINS_LOADING = "GET_COMPLAINS_LOADING";

// trainings 
export const  CREATE_TRAINING_SUCCESS = "CREATE_TRAINING_SUCCESS";
export const  CREATE_TRAINING_LOADING = "CREATE_TRAINING_LOADING";
export const  CREATE_TRAINING_FAILED = "CREATE_TRAINING_FAILED";
export const  UPDATE_TRAINING_SUCCESS = "UPDATE_TRAINING_SUCCESS";
export const  UPDATE_TRAINING_LOADING = "UPDATE_TRAINING_LOADING";
export const  UPDATE_TRAINING_FAILED = "UPDATE_TRAINING_FAILED";
export const  DELETE_TRAINING_SUCCESS = "DELETE_TRAINING_SUCCESS";
export const  DELETE_TRAINING_FAILED = "DELETE_TRAINING_FAILED";
export const  DELETE_TRAINING_LOADING = "DELETE_TRAINING_LOADING";
export const  GET_TRAINING_SUCCESS = "GET_TRAINING_SUCCESS";
export const  GET_TRAINING_FAILED = "GET_TRAINING_FAILED";
export const  GET_TRAINING_LOADING = "GET_TRAINING_LOADING";
export const  GET_TRAININGS_SUCCESS = "GET_TRAININGS_SUCCESS";
export const  GET_TRAININGS_FAILED = "GET_TRAININGS_FAILED";
export const  GET_TRAININGS_LOADING = "GET_TRAININGS_LOADING";

//events 

export const  CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const  CREATE_EVENT_LOADING = "CREATE_EVENT_LOADING";
export const  CREATE_EVENT_FAILED = "CREATE_EVENT_FAILED";
export const  UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const  UPDATE_EVENT_LOADING = "UPDATE_EVENT_LOADING";
export const  UPDATE_EVENT_FAILED = "UPDATE_EVENT_FAILED";
export const  DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const  DELETE_EVENT_FAILED = "DELETE_EVENT_FAILED";
export const  DELETE_EVENT_LOADING = "DELETE_EVENT_LOADING";
export const  GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const  GET_EVENT_FAILED = "GET_EVENT_FAILED";
export const  GET_EVENT_LOADING = "GET_EVENT_LOADING";
export const  GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const  GET_EVENTS_FAILED = "GET_EVENTS_FAILED";
export const  GET_EVENTS_LOADING = "GET_EVENTS_LOADING";

//lectures views

export const  CREATE_LECTURE_VIEW_SUCCESS = "CREATE_LECTURE_VIEW_SUCCESS";
export const  CREATE_LECTURE_VIEW_LOADING = "CREATE_LECTURE_VIEW_LOADING";
export const  CREATE_LECTURE_VIEW_FAILED = "CREATE_LECTURE_VIEW_FAILED";
export const  UPDATE_LECTURE_VIEW_SUCCESS = "UPDATE_LECTURE_VIEW_SUCCESS";
export const  UPDATE_LECTURE_VIEW_LOADING = "UPDATE_LECTURE_VIEW_LOADING";
export const  UPDATE_LECTURE_VIEW_FAILED = "UPDATE_LECTURE_VIEW_FAILED";
export const  DELETE_LECTURE_VIEW_SUCCESS = "DELETE_LECTURE_VIEW_SUCCESS";
export const  DELETE_LECTURE_VIEW_FAILED = "DELETE_LECTURE_VIEW_FAILED";
export const  DELETE_LECTURE_VIEW_LOADING = "DELETE_LECTURE_VIEW_LOADING";
export const  GET_LECTURE_VIEW_SUCCESS = "GET_LECTURE_VIEW_SUCCESS";
export const  GET_LECTURE_VIEW_FAILED = "GET_LECTURE_VIEW_FAILED";
export const  GET_LECTURE_VIEW_LOADING = "GET_LECTURE_VIEW_LOADING";
export const  GET_LECTURE_VIEWS_SUCCESS = "GET_LECTURE_VIEWS_SUCCESS";
export const  GET_LECTURE_VIEWS_FAILED = "GET_LECTURE_VIEWS_FAILED";
export const  GET_LECTURE_VIEWS_LOADING = "GET_LECTURE_VIEWS_LOADING";

//lectures

export const  CREATE_LECTURE_SUCCESS = "CREATE_LECTURE_SUCCESS";
export const  CREATE_LECTURE_LOADING = "CREATE_LECTURE_LOADING";
export const  CREATE_LECTURE_FAILED = "CREATE_LECTURE_FAILED";
export const  UPDATE_LECTURE_SUCCESS = "UPDATE_LECTURE_SUCCESS";
export const  UPDATE_LECTURE_LOADING = "UPDATE_LECTURE_LOADING";
export const  UPDATE_LECTURE_FAILED = "UPDATE_LECTURE_FAILED";
export const  DELETE_LECTURE_SUCCESS = "DELETE_LECTURE_SUCCESS";
export const  DELETE_LECTURE_FAILED = "DELETE_LECTURE_FAILED";
export const  DELETE_LECTURE_LOADING = "DELETE_LECTURE_LOADING";
export const  GET_LECTURE_SUCCESS = "GET_LECTURE_SUCCESS";
export const  GET_LECTURE_FAILED = "GET_LECTURE_FAILED";
export const  GET_LECTURE_LOADING = "GET_LECTURE_LOADING";
export const  GET_LECTURES_SUCCESS = "GET_LECTURES_SUCCESS";
export const  GET_LECTURES_FAILED = "GET_LECTURES_FAILED";
export const  GET_LECTURES_LOADING = "GET_LECTURES_LOADING";

//modules

export const  CREATE_MODULE_SUCCESS = "CREATE_MODULE_SUCCESS";
export const  CREATE_MODULE_LOADING = "CREATE_MODULE_LOADING";
export const  CREATE_MODULE_FAILED = "CREATE_MODULE_FAILED";
export const  UPDATE_MODULE_SUCCESS = "UPDATE_MODULE_SUCCESS";
export const  UPDATE_MODULE_LOADING = "UPDATE_MODULE_LOADING";
export const  UPDATE_MODULE_FAILED = "UPDATE_MODULE_FAILED";
export const  DELETE_MODULE_SUCCESS = "DELETE_MODULE_SUCCESS";
export const  DELETE_MODULE_FAILED = "DELETE_MODULE_FAILED";
export const  DELETE_MODULE_LOADING = "DELETE_MODULE_LOADING";
export const  GET_MODULE_SUCCESS = "GET_MODULE_SUCCESS";
export const  GET_MODULE_FAILED = "GET_MODULE_FAILED";
export const  GET_MODULE_LOADING = "GET_MODULE_LOADING";
export const  GET_MODULES_SUCCESS = "GET_MODULES_SUCCESS";
export const  GET_MODULES_FAILED = "GET_MODULES_FAILED";
export const  GET_MODULES_LOADING = "GET_MODULES_LOADING";

// news 

export const  CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";
export const  CREATE_NEWS_LOADING = "CREATE_NEWS_LOADING";
export const  CREATE_NEWS_FAILED = "CREATE_NEWS_FAILED";
export const  UPDATE_NEWS_SUCCESS = "UPDATE_NEWS_SUCCESS";
export const  UPDATE_NEWS_LOADING = "UPDATE_NEWS_LOADING";
export const  UPDATE_NEWS_FAILED = "UPDATE_NEWS_FAILED";
export const  DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const  DELETE_NEWS_FAILED = "DELETE_NEWS_FAILED";
export const  DELETE_NEWS_LOADING = "DELETE_NEWS_LOADING";
export const  GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const  GET_NEWS_FAILED = "GET_NEWS_FAILED";
export const  GET_NEWS_LOADING = "GET_NEWS_LOADING";
export const  GET_NEWSES_SUCCESS = "GET_NEWSES_SUCCESS";
export const  GET_NEWSES_FAILED = "GET_NEWSES_FAILED";
export const  GET_NEWSES_LOADING = "GET_NEWSES_LOADING";

//payment
export const  CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const  CREATE_PAYMENT_LOADING = "CREATE_PAYMENT_LOADING";
export const  CREATE_PAYMENT_FAILED = "CREATE_PAYMENT_FAILED";
export const  UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const  UPDATE_PAYMENT_LOADING = "UPDATE_PAYMENT_LOADING";
export const  UPDATE_PAYMENT_FAILED = "UPDATE_PAYMENT_FAILED";
export const  DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const  DELETE_PAYMENT_FAILED = "DELETE_PAYMENT_FAILED";
export const  DELETE_PAYMENT_LOADING = "DELETE_PAYMENT_LOADING";
export const  GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const  GET_PAYMENT_FAILED = "GET_PAYMENT_FAILED";
export const  GET_PAYMENT_LOADING = "GET_PAYMENT_LOADING";
export const  GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";
export const  GET_PAYMENTS_FAILED = "GET_PAYMENTS_FAILED";
export const  GET_PAYMENTS_LOADING = "GET_PAYMENTS_LOADING";

//permission
export const  CREATE_PERMISSION_SUCCESS = "CREATE_PERMISSION_SUCCESS";
export const  CREATE_PERMISSION_LOADING = "CREATE_PERMISSION_LOADING";
export const  CREATE_PERMISSION_FAILED = "CREATE_PERMISSION_FAILED";
export const  UPDATE_PERMISSION_SUCCESS = "UPDATE_PERMISSION_SUCCESS";
export const  UPDATE_PERMISSION_LOADING = "UPDATE_PERMISSION_LOADING";
export const  UPDATE_PERMISSION_FAILED = "UPDATE_PERMISSION_FAILED";
export const  DELETE_PERMISSION_SUCCESS = "DELETE_PERMISSION_SUCCESS";
export const  DELETE_PERMISSION_FAILED = "DELETE_PERMISSION_FAILED";
export const  DELETE_PERMISSION_LOADING = "DELETE_PERMISSION_LOADING";
export const  GET_PERMISSION_SUCCESS = "GET_PERMISSION_SUCCESS";
export const  GET_PERMISSION_FAILED = "GET_PERMISSION_FAILED";
export const  GET_PERMISSION_LOADING = "GET_PERMISSION_LOADING";
export const  GET_PERMISSIONS_SUCCESS = "GET_PERMISSIONS_SUCCESS";
export const  GET_PERMISSIONS_FAILED = "GET_PERMISSIONS_FAILED";
export const  GET_PERMISSIONS_LOADING = "GET_PERMISSIONS_LOADING";

// promo
export const  CREATE_PROMO_SUCCESS = "CREATE_PROMO_SUCCESS";
export const  CREATE_PROMO_LOADING = "CREATE_PROMO_LOADING";
export const  CREATE_PROMO_FAILED = "CREATE_PROMO_FAILED";
export const  UPDATE_PROMO_SUCCESS = "UPDATE_PROMO_SUCCESS";
export const  UPDATE_PROMO_LOADING = "UPDATE_PROMO_LOADING";
export const  UPDATE_PROMO_FAILED = "UPDATE_PROMO_FAILED";
export const  DELETE_PROMO_SUCCESS = "DELETE_PROMO_SUCCESS";
export const  DELETE_PROMO_FAILED = "DELETE_PROMO_FAILED";
export const  DELETE_PROMO_LOADING = "DELETE_PROMO_LOADING";
export const  GET_PROMO_SUCCESS = "GET_PROMO_SUCCESS";
export const  GET_PROMO_FAILED = "GET_PROMO_FAILED";
export const  GET_PROMO_LOADING = "GET_PROMO_LOADING";
export const  GET_PROMOS_SUCCESS = "GET_PROMOS_SUCCESS";
export const  GET_PROMOS_FAILED = "GET_PROMOS_FAILED";
export const  GET_PROMOS_LOADING = "GET_PROMOS_LOADING";

// publication 
export const  CREATE_PUBLICATION_SUCCESS = "CREATE_PUBLICATION_SUCCESS";
export const  CREATE_PUBLICATION_LOADING = "CREATE_PUBLICATION_LOADING";
export const  CREATE_PUBLICATION_FAILED = "CREATE_PUBLICATION_FAILED";
export const  UPDATE_PUBLICATION_SUCCESS = "UPDATE_PUBLICATION_SUCCESS";
export const  UPDATE_PUBLICATION_LOADING = "UPDATE_PUBLICATION_LOADING";
export const  UPDATE_PUBLICATION_FAILED = "UPDATE_PUBLICATION_FAILED";
export const  DELETE_PUBLICATION_SUCCESS = "DELETE_PUBLICATION_SUCCESS";
export const  DELETE_PUBLICATION_FAILED = "DELETE_PUBLICATION_FAILED";
export const  DELETE_PUBLICATION_LOADING = "DELETE_PUBLICATION_LOADING";
export const  GET_PUBLICATION_SUCCESS = "GET_PUBLICATION_SUCCESS";
export const  GET_PUBLICATION_FAILED = "GET_PUBLICATION_FAILED";
export const  GET_PUBLICATION_LOADING = "GET_PUBLICATION_LOADING";
export const  GET_PUBLICATIONS_SUCCESS = "GET_PUBLICATIONS_SUCCESS";
export const  GET_PUBLICATIONS_FAILED = "GET_PUBLICATIONS_FAILED";
export const  GET_PUBLICATIONS_LOADING = "GET_PUBLICATIONS_LOADING";

//quiz

export const  CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const  CREATE_QUIZ_LOADING = "CREATE_QUIZ_LOADING";
export const  CREATE_QUIZ_FAILED = "CREATE_QUIZ_FAILED";
export const  UPDATE_QUIZ_SUCCESS = "UPDATE_QUIZ_SUCCESS";
export const  UPDATE_QUIZ_LOADING = "UPDATE_QUIZ_LOADING";
export const  UPDATE_QUIZ_FAILED = "UPDATE_QUIZ_FAILED";
export const  DELETE_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";
export const  DELETE_QUIZ_FAILED = "DELETE_QUIZ_FAILED";
export const  DELETE_QUIZ_LOADING = "DELETE_QUIZ_LOADING";
export const  GET_QUIZ_SUCCESS = "GET_QUIZ_SUCCESS";
export const  GET_QUIZ_FAILED = "GET_QUIZ_FAILED";
export const  GET_QUIZ_LOADING = "GET_QUIZ_LOADING";
export const  GET_QUIZES_SUCCESS = "GET_QUIZES_SUCCESS";
export const  GET_QUIZES_FAILED = "GET_QUIZES_FAILED";
export const  GET_QUIZES_LOADING = "GET_QUIZES_LOADING";

//review
export const  CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const  CREATE_REVIEW_LOADING = "CREATE_REVIEW_LOADING";
export const  CREATE_REVIEW_FAILED = "CREATE_REVIEW_FAILED";
export const  UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const  UPDATE_REVIEW_LOADING = "UPDATE_REVIEW_LOADING";
export const  UPDATE_REVIEW_FAILED = "UPDATE_REVIEW_FAILED";
export const  DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const  DELETE_REVIEW_FAILED = "DELETE_REVIEW_FAILED";
export const  DELETE_REVIEW_LOADING = "DELETE_REVIEW_LOADING";
export const  GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const  GET_REVIEW_FAILED = "GET_REVIEW_FAILED";
export const  GET_REVIEW_LOADING = "GET_REVIEW_LOADING";
export const  GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const  GET_REVIEWS_FAILED = "GET_REVIEWS_FAILED";
export const  GET_REVIEWS_LOADING = "GET_REVIEWS_LOADING";

//role

export const  CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const  CREATE_ROLE_LOADING = "CREATE_ROLE_LOADING";
export const  CREATE_ROLE_FAILED = "CREATE_ROLE_FAILED";
export const  UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const  UPDATE_ROLE_LOADING = "UPDATE_ROLE_LOADING";
export const  UPDATE_ROLE_FAILED = "UPDATE_ROLE_FAILED";
export const  DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const  DELETE_ROLE_FAILED = "DELETE_ROLE_FAILED";
export const  DELETE_ROLE_LOADING = "DELETE_ROLE_LOADING";
export const  GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const  GET_ROLE_FAILED = "GET_ROLE_FAILED";
export const  GET_ROLE_LOADING = "GET_ROLE_LOADING";
export const  GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const  GET_ROLES_FAILED = "GET_ROLES_FAILED";
export const  GET_ROLES_LOADING = "GET_ROLES_LOADING";

//subscription
export const  CREATE_SUBSCRIPTION_SUCCESS = "CREATE_SUBSCRIPTION_SUCCESS";
export const  CREATE_SUBSCRIPTION_LOADING = "CREATE_SUBSCRIPTION_LOADING";
export const  CREATE_SUBSCRIPTION_FAILED = "CREATE_SUBSCRIPTION_FAILED";
export const  UPDATE_SUBSCRIPTION_SUCCESS = "UPDATE_SUBSCRIPTION_SUCCESS";
export const  UPDATE_SUBSCRIPTION_LOADING = "UPDATE_SUBSCRIPTION_LOADING";
export const  UPDATE_SUBSCRIPTION_FAILED = "UPDATE_SUBSCRIPTION_FAILED";
export const  DELETE_SUBSCRIPTION_SUCCESS = "DELETE_SUBSCRIPTION_SUCCESS";
export const  DELETE_SUBSCRIPTION_FAILED = "DELETE_SUBSCRIPTION_FAILED";
export const  DELETE_SUBSCRIPTION_LOADING = "DELETE_SUBSCRIPTION_LOADING";
export const  GET_SUBSCRIPTION_SUCCESS = "GET_SUBSCRIPTION_SUCCESS";
export const  GET_SUBSCRIPTION_FAILED = "GET_SUBSCRIPTION_FAILED";
export const  GET_SUBSCRIPTION_LOADING = "GET_SUBSCRIPTION_LOADING";
export const  GET_SUBSCRIPTIONS_SUCCESS = "GET_SUBSCRIPTIONS_SUCCESS";
export const  GET_SUBSCRIPTIONS_FAILED = "GET_SUBSCRIPTIONS_FAILED";
export const  GET_SUBSCRIPTIONS_LOADING = "GET_SUBSCRIPTIONS_LOADING";

